### PR TITLE
archive day 2 email

### PR DESCRIPTION
**Pull request by bast**
@MatiasJJ

### CODE REVIEW

**Comment by dianaiusan** [comment]
you have beaten me with 1 min

**Comment by dianaiusan** [comment]
looks good, I'll let @MatiasJJ merge as he has done the email work 🙏

**Comment by bast** [comment]
Sorry I did not know you were working on it.

**Comment by dianaiusan** [comment]
no problem, Radovan, I did not officially WIP it.

**Comment by bast** [comment]
Merged since I am referring to it in today's email.

**Pull request merged**
